[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/slides/1025-vue-tw-slidev/*"
  to = "/slides/1025-vue-tw-slidev/index.html"
  status = 200

